<a href="https://colab.research.google.com/github/ConsueloFarias/proyecto-final-consuelo-v2/blob/main/clasesCoder/Clase_3_21_Julio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
array_unidimensional = np.array ([1,2,3,4,5])


In [ ]:
print(array_unidimensional)

[1 2 3 4 5]


In [ ]:
array_bidimesional = np.zeros((2,3))

In [ ]:
print(array_bidimesional)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
array_zeros = np.zeros(5)

In [ ]:
array_ones = np.ones(5)

In [ ]:
array_full = np.full(5,7)

In [ ]:
print(array_zeros)

[0. 0. 0. 0. 0.]


In [ ]:
print(array_ones)

[1. 1. 1. 1. 1.]


In [ ]:
print(array_full)

[7 7 7 7 7]


In [ ]:
import numpy as np

# Crear un ndarray de ceros con 10 elementos
arr = np.zeros(10)

print(arr.ndim)       # Output: 1 (una dimensión)
print(arr.shape)      # Output: (10,) (10 elementos en una sola dimensión)
print(arr.size)       # Output: 10 (10 elementos en total)
print(arr.dtype)      # Output: float64 (tipo de dato de los elementos)
print(arr.itemsize)   # Output: 8 (cada elemento ocupa 8 bytes)
print(arr.nbytes)     # Output: 80 (10 elementos * 8 bytes por elemento)

1
(10,)
10
float64
8
80


In [ ]:
arr = np.arange(12)

In [ ]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
arr_reshaped = arr.reshape((3,4))

In [ ]:
print(arr_reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:

# Crear dos arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenar los arrays horizontalmente (por defecto)
arr_concatenated = np.concatenate((arr1, arr2))

print(arr_concatenated)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

# Crear un array de 9 elementos
arr = np.arange(9)

print(arr)

[0 1 2 3 4 5 6 7 8]


In [ ]:
# Dividir el array en 3 subarrays
arr_split = np.split(arr, 3)

print(arr_split)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [ ]:
# Dividir el array en 3 subarrays
arr_split = np.hsplit(arr, 3)

print(arr_split)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [2]:
import pandas as pd